/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
export module ui {
    export class loadingUI extends Laya.Scene {
        public static  uiView:any ={"type":"Scene","props":{"width":300,"height":200},"compId":2,"child":[{"type":"Image","props":{"y":-7,"x":-28,"skin":"gameui/img_dizuo.png"},"compId":3}],"loadList":["gameui/img_dizuo.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(loadingUI.uiView);
        }
    }
    export class testUI extends Laya.Scene {
		public btn1:Laya.Button;
		public btn2:Laya.Button;
		public img:Laya.Image;
        public static  uiView:any ={"type":"Scene","props":{"width":1136,"height":640},"compId":2,"child":[{"type":"Button","props":{"y":280,"x":294,"var":"btn1","skin":"comp/button.png","label":"加载图集"},"compId":3},{"type":"Button","props":{"y":280,"x":406.5,"var":"btn2","skin":"comp/button.png","label":"卸载图集"},"compId":4},{"type":"Image","props":{"width":200,"var":"img","height":200},"compId":7}],"loadList":["comp/button.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(testUI.uiView);
        }
    }
}